---
title: "Mapping Méléard and Roelly (1992) to Week et. al."
output:
  pdf_document:
    toc: false
    number_sections: true
    fig_width: 4
    fig_height: 3
    fig_caption: true
header-includes:
  - \usepackage{float}
  - \usepackage{mathrsfs}
  - \usepackage{hyperref}
  - \usepackage[left]{lineno}
  - \usepackage{amsmath}
  - \usepackage{makecell}
  - \usepackage{arydshln}
editor_options: 
  chunk_output_type: console
---

\begin{table}[H]
\begin{tabular}{l|l|l}
Description           & Méléard and Roelly 92 & Week et al    \\ \hline
&& \\
Arbitrary finite measure & $\mu\in M_F(\mathbb{R}^d)$ & NA \\ \hdashline
&& \\
Bounded function & $f\in C_b(\mathbb{R}^d)$ & $f\in C_b(\mathbb{R})$ \\ \hdashline
&& \\
\makecell{Non-negative continuous \\ integrable function} & NA & $\nu(\cdot,t)\in C_1^+(\mathbb{R})$ \\ \hdashline
&& \\
"Spatial" location    & $x\in\mathbb{R}^d$ & $x\in\mathbb{R}\dots$ \makecell{interpreted as \\ trait value} \\ \hdashline
&& \\
\makecell{Infinitesimal generator \\ of spatial movement} & \makecell{$A(\mu)\dots$ \\ satisfies ($\mathrm{H}_1$) and ($\mathrm{H}_2$) below} & \makecell{$\frac{\mu}{2}\Delta\dots$ Laplace operator \\ with diffusion coefficient $\mu/2$} \\ \hdashline
&& \\
Superprocess          & $X_t\in M_F(\mathbb{R}^d)$ for $t\in[0,\infty)$ & NA                      \\ \hdashline
&& \\
Density process       & NA               & $\nu(x,t)$              \\ \hdashline
&& \\
Duality bracket       & $\begin{matrix}\langle X_t,f\rangle\dots \\ X_t\in M_F(\mathbb{R}^d), \ f\in C_b(\mathbb{R}^d)\end{matrix}$ & $\begin{matrix}\int_\mathbb{R}\nu(x,t)f(x)dx\dots \\ \nu(\cdot,t)\in C_1^+(\mathbb{R}), \ f\in C^2_b(\mathbb{R})\end{matrix}$ \\ \hdashline
&& \\
Malthusian parameter  & \makecell{$b(\mu)(x)\dots \ b(\mu)\in C_b(\mathbb{R}^d)$ \\ for $\mu\in M_F(\mathbb{R}^d)$} & $m\big(\nu(x,t),x\big)\dots$ \makecell{bounded above, \\ but not below} \\ \hdashline
&& \\
Stochastic parameter  & \makecell{$c(\mu)(x)\dots \ c(\mu)\in C_b(\mathbb{R}^d)$ \\ for $\mu\in M_F(\mathbb{R}^d)$} & $V>0\dots$ constant \\ \hdashline
&& \\
Reproductive law      & $p_k(x,\mu)$ & NA \\ \hdashline
&& \\
Mean of reproductive law & $\begin{matrix}m(x,\mu)=\sum_{k\in\mathbb{N}}kp_k(x,\mu)\dots \\ \sup_{x,\mu}|m(x,\mu)|<\infty\end{matrix}$ & $\begin{matrix}\mathscr{W}(\nu,x)\dots\\\sup_{\nu,x}\mathscr{W}(\nu,x)<\infty\end{matrix}$ \makecell{introduced in \\ appendix} \\ \hdashline
&& \\
Unnamed                  & $v^2(x,\mu)=\sum_{k\in\mathbb{N}}(k-1)^2p_k(x,\mu)$ & NA \\ \hdashline
&& \\
Death rate               & $\lambda(x,\mu)$ & we assume constant "lifetimes"
\end{tabular}\label{mult}
\end{table}
\newpage
\section*{Notes}

- ($\mathrm{H}_1$): For all $\mu\in M_F(\mathbb{R}^d)$ and all $f$ in the domain of $A(\mu)$, there is a constant $K>0$ such that $\|A(\mu)f\|_\infty\leq K\langle\mu,1\rangle$.

- ($\mathrm{H}_2$): For all $f$ in the domain of $A(\mu)$, the map $\mu\to\langle\mu,A(\mu)f\rangle$ is continuous.

- In Week et al, spatial movement is interpreted as mutation. Hence, durations of spatial movement are not interpreted as lifetimes. Instead, we assume discrete non-overlapping generations for the branching diffusion process.

- In Champagnat, Ferrière and Méléard (2006) the condition $\sup_{x,\mu}|m(x,\mu)|<\infty$ has been weakened to $\sup_{x,\mu}m(x,\mu)<\infty$ and $\ln m(x,\mu)\geq C(1+\mu(\mathbb{R}^d))$ for some constant $K>0$ which they refer to as being linear or "more than linear".